version: '3.9'

services:
  postgres:
    image: postgres:17-alpine
    container_name: simco-stats-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - simco_stats_data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - nestjs-network

volumes:
  simco_stats_data:
    name: simco-stats-data

networks:
  nestjs-network:
    name: simco-stats-network
    driver: bridge
